name: Build 
on:
    push:
    schedule:
        - cron: '0 0 * * *'
    workflow_dispatch:

jobs:
    build:
        name: Build Engine
        runs-on: macos-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4
            - name: Run bash script
              run: |
                  ./build.sh
            - name: Upload Archive
              uses: actions/upload-artifact@v4
              with:
                  name: WineBuild
                  path: WineBuild.txz
